### ISSUE TITLE
Install does not install transitively-required headers

### ISSUE THREAD

**Issue by dascandy** [wolkykim/libasyncd#17]
When including asyncd/ad_server.h it complains about qlibc's headers. Can you also install qlibc if it is not already there, when you do make install? Otherwise you get an unusable install.

**Comment by wolkykim** [comment]
That's a good point. Let me see what I can do for this.

**Comment by dascandy** [comment]
So far I just did a cp -R of the relevant include folder and that seems to work for compiling - didn't get to linking yet.

**Comment by codebrainz** [comment]
[The link](http://www.gnu.org/software/automake/manual/html_node/Subpackages.html) in my last comment on #13 would solve this, thought it probably requires using Automake.

**Comment by wolkykim** [comment]
Introducing "install-libs" target rather than forcing the install due to some possible overwrite if users are using custom-built qlibc already.

# make install
(cd src/; make install)
make[1]: Entering directory `/home/wolkykim/ws/libasyncd/src'
/bin/mkdir -p /usr/local/include/asyncd
/usr/bin/install -c -m 644 ../include/asyncd/asyncd.h /usr/local/include/asyncd/asyncd.h
/usr/bin/install -c -m 644 ../include/asyncd/ad_server.h /usr/local/include/asyncd/ad_server.h
/usr/bin/install -c -m 644 ../include/asyncd/ad_http_handler.h /usr/local/include/asyncd/ad_http_handler.h
/bin/mkdir -p /usr/local/lib
/usr/bin/install -c -m 644 libasyncd.a /usr/local/lib/libasyncd.a
/usr/bin/install -c -m 644 libasyncd.so.1 /usr/local/lib/libasyncd.so.1
( cd /usr/local/lib; ln -s -f libasyncd.so.1 libasyncd.so )
make[1]: Leaving directory `/home/wolkykim/ws/libasyncd/src'
=======================================================
Run 'make install-libs' to install dependent libraries.
=======================================================
